#!/usr/bin/env bash
# Confirms the repo tree contains no third-party-tool authorship attribution.
# Exits 0 with a clean message if no hits, 1 with a list of files otherwise.

set -euo pipefail

patterns='generated by claude|built with claude|co-authored-by[[:space:]]*claude|ai-generated|anthropic\.com|chatgpt[[:space:]]+wrote|claude code (made|wrote|created|built)'

# Search everything except .git, marketing/dist (build output), and this script
# itself (which by definition contains the patterns it searches for).
hits=$(grep -rniE "$patterns" . \
  --exclude-dir=.git \
  --exclude-dir=dist \
  --exclude="audit-tree.sh" \
  2>/dev/null || true)

if [[ -z "$hits" ]]; then
  echo "✓ clean — no third-party authorship strings in tree"
  exit 0
fi

echo "✗ found the following lines:" >&2
echo "$hits" >&2
exit 1
